-- AlterTable
ALTER TABLE `PROYECTO_PROYECCION_SOCIAL` MODIFY `tipo_mime` VARCHAR(100) NULL,
    MODIFY `archivo` LONGBLOB NULL;

-- CreateTable
CREATE TABLE `INTEGRANTE_PROYECTO_SOCIAL` (
    `id_integrante` VARCHAR(191) NOT NULL,
    `id_proyecto_social` VARCHAR(191) NOT NULL,
    `id_persona` VARCHAR(191) NOT NULL,
    `rol` VARCHAR(50) NOT NULL,

    INDEX `INTEGRANTE_PROYECTO_SOCIAL_id_proyecto_social_idx`(`id_proyecto_social`),
    INDEX `INTEGRANTE_PROYECTO_SOCIAL_id_persona_idx`(`id_persona`),
    PRIMARY KEY (`id_integrante`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `INTEGRANTE_PROYECTO_SOCIAL` ADD CONSTRAINT `INTEGRANTE_PROYECTO_SOCIAL_id_proyecto_social_fkey` FOREIGN KEY (`id_proyecto_social`) REFERENCES `PROYECTO_PROYECCION_SOCIAL`(`id_proyecto_social`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `INTEGRANTE_PROYECTO_SOCIAL` ADD CONSTRAINT `INTEGRANTE_PROYECTO_SOCIAL_id_persona_fkey` FOREIGN KEY (`id_persona`) REFERENCES `PERSONA`(`id_persona`) ON DELETE RESTRICT ON UPDATE CASCADE;
