services:
    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile
        container_name: unimayor_backend
        restart: always
        ports:
            - "5050:5050"
        environment:
            - NODE_ENV=production
            - PORT=5050
        env_file:
            - ./backend/.env

    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile
        container_name: unimayor_frontend
        restart: always
        ports:
            - "3000:3000"
        environment:
            - NODE_ENV=production
            - PORT=3000
        env_file:
            - ./frontend/.env
        depends_on:
            - backend
