version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: unimayor_backend
    restart: always
    ports:
      - "5050:5050"
    environment:
      - NODE_ENV=production
      - PORT=5050
      # Make sure to copy the .env variables here or use env_file
    env_file:
      - ./backend/.env.local # Uses your local variables for the DB connection

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: unimayor_frontend
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    env_file:
      - ./frontend/.env.local
    depends_on:
      - backend
