-- CreateTable
CREATE TABLE `PERSONA` (
    `CARNET` VARCHAR(191) NOT NULL,
    `NOMBRES` VARCHAR(191) NOT NULL,
    `APELLIDOS` VARCHAR(191) NOT NULL,
    `TIPO_DOC_IDENTIDAD` VARCHAR(191) NOT NULL,
    `NUM_DOC_IDENTIDAD` VARCHAR(191) NOT NULL,
    `EMAIL_INSTITUCIONAL` VARCHAR(191) NOT NULL,
    `TELEFONO` VARCHAR(191) NULL,
    `TIPO_VINCULACION` VARCHAR(191) NOT NULL,
    `AREA_ESPECIALIZACION` VARCHAR(191) NULL,
    `FECHA_REGISTRO` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    UNIQUE INDEX `PERSONA_NUM_DOC_IDENTIDAD_key`(`NUM_DOC_IDENTIDAD`),
    UNIQUE INDEX `PERSONA_EMAIL_INSTITUCIONAL_key`(`EMAIL_INSTITUCIONAL`),
    PRIMARY KEY (`CARNET`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `FACULTAD` (
    `ID_FACULTAD` INTEGER NOT NULL AUTO_INCREMENT,
    `NOMBRE_FACULTAD` VARCHAR(191) NOT NULL,
    `CODIGO_FACULTAD` VARCHAR(191) NOT NULL,

    UNIQUE INDEX `FACULTAD_CODIGO_FACULTAD_key`(`CODIGO_FACULTAD`),
    PRIMARY KEY (`ID_FACULTAD`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `PROGRAMA_ACADEMICO` (
    `ID_PROGRAMA_ACADEMICO` INTEGER NOT NULL AUTO_INCREMENT,
    `NOMBRE_PROGRAMA` VARCHAR(191) NOT NULL,
    `CODIGO_SNIES` VARCHAR(191) NOT NULL,
    `ESTADO` VARCHAR(191) NOT NULL,
    `ID_FACULTAD` INTEGER NOT NULL,

    UNIQUE INDEX `PROGRAMA_ACADEMICO_CODIGO_SNIES_key`(`CODIGO_SNIES`),
    PRIMARY KEY (`ID_PROGRAMA_ACADEMICO`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `NIVEL_FORMACION` (
    `ID_NIVEL_FORMACION` INTEGER NOT NULL AUTO_INCREMENT,
    `NOMBRE_NIVEL` VARCHAR(191) NOT NULL,
    `DESCRIPCION` VARCHAR(191) NULL,

    PRIMARY KEY (`ID_NIVEL_FORMACION`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `PROGRAMA_NIVEL` (
    `ID_PROGRAMA_NIVEL` INTEGER NOT NULL AUTO_INCREMENT,
    `ID_PROGRAMA_ACADEMICO` INTEGER NOT NULL,
    `ID_NIVEL_FORMACION` INTEGER NOT NULL,
    `ESTADO` VARCHAR(191) NOT NULL,

    PRIMARY KEY (`ID_PROGRAMA_NIVEL`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `OPCION_GRADO` (
    `ID_OPCION_GRADO` INTEGER NOT NULL AUTO_INCREMENT,
    `NOMBRE_OPCION_GRADO` VARCHAR(191) NOT NULL,
    `DESCRIPCION_OPCION` VARCHAR(191) NULL,
    `ESTADO` VARCHAR(191) NOT NULL,
    `ID_PROGRAMA_NIVEL` INTEGER NOT NULL,

    PRIMARY KEY (`ID_OPCION_GRADO`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `ESTUDIANTE_PROGRAMA` (
    `CARNET` VARCHAR(191) NOT NULL,
    `ID_PROGRAMA_ACADEMICO` INTEGER NOT NULL,
    `PORC_CREDITOS_APROBADOS` INTEGER NOT NULL,
    `ESTADO_ACADEMICO` VARCHAR(191) NOT NULL,
    `FECHA_INGRESO` DATETIME(3) NOT NULL,
    `FECHA_EGRESO` DATETIME(3) NULL,

    PRIMARY KEY (`CARNET`, `ID_PROGRAMA_ACADEMICO`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `TRABAJO_GRADO` (
    `ID_TRABAJO_GRADO` INTEGER NOT NULL AUTO_INCREMENT,
    `TITULO_TRABAJO` VARCHAR(191) NOT NULL,
    `FECHA_INICIO` DATETIME(3) NOT NULL,
    `FECHA_FIN_ESTIMADA` DATETIME(3) NULL,
    `RESUMEN` VARCHAR(191) NULL,
    `ESTADO` VARCHAR(191) NOT NULL,
    `ID_OPCION_GRADO` INTEGER NOT NULL,
    `ID_ESTADO_ACTUAL` INTEGER NOT NULL,

    PRIMARY KEY (`ID_TRABAJO_GRADO`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `TIPO_ROL` (
    `ID_TIPO_ROL` INTEGER NOT NULL AUTO_INCREMENT,
    `NOMBRE_ROL` VARCHAR(191) NOT NULL,
    `DESCRIPCION` VARCHAR(191) NULL,

    PRIMARY KEY (`ID_TIPO_ROL`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `ROL_PERSONA_TG` (
    `ID_ROL_PERSONA` INTEGER NOT NULL AUTO_INCREMENT,
    `CARNET` VARCHAR(191) NOT NULL,
    `ID_TRABAJO_GRADO` INTEGER NOT NULL,
    `ID_TIPO_ROL` INTEGER NOT NULL,
    `FECHA_ASIGNACION` DATETIME(3) NOT NULL,
    `FECHA_RETIRO` DATETIME(3) NULL,
    `ESTADO` VARCHAR(191) NOT NULL,
    `OBSERVACIONES` VARCHAR(191) NULL,

    PRIMARY KEY (`ID_ROL_PERSONA`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `ESTADO_TG` (
    `ID_ESTADO_TG` INTEGER NOT NULL AUTO_INCREMENT,
    `NOMBRE_ESTADO` VARCHAR(191) NOT NULL,
    `DESCRIPCION` VARCHAR(191) NULL,
    `ORDEN` INTEGER NOT NULL,

    PRIMARY KEY (`ID_ESTADO_TG`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `SEGUIMIENTO_TG` (
    `ID_SEGUIMIENTO` INTEGER NOT NULL AUTO_INCREMENT,
    `ID_TRABAJO_GRADO` INTEGER NOT NULL,
    `CARNET_ACTOR` VARCHAR(191) NOT NULL,
    `FECHA_REGISTRO` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `TIPO_ACCION` VARCHAR(191) NOT NULL,
    `DESCRIPCION` VARCHAR(191) NULL,
    `DETALLE` VARCHAR(191) NULL,
    `ID_ESTADO_ANTERIOR` INTEGER NULL,
    `ID_ESTADO_NUEVO` INTEGER NULL,
    `NUMERO_OFICIO` VARCHAR(191) NULL,
    `FECHA_OFICIO` DATETIME(3) NULL,
    `NOMBRE_DOCUMENTO` VARCHAR(191) NULL,
    `TIPO_DOCUMENTO` VARCHAR(191) NULL,
    `ARCHIVO` LONGBLOB NULL,
    `RUTA_ARCHIVO` VARCHAR(191) NULL,

    PRIMARY KEY (`ID_SEGUIMIENTO`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `EMPRESA` (
    `ID_EMPRESA` INTEGER NOT NULL AUTO_INCREMENT,
    `NIT_EMPRESA` VARCHAR(191) NOT NULL,
    `NOMBRE_EMPRESA` VARCHAR(191) NOT NULL,
    `DIRECCION` VARCHAR(191) NOT NULL,
    `TELEFONO` VARCHAR(191) NOT NULL,
    `EMAIL_CONTACTO` VARCHAR(191) NOT NULL,
    `ESTADO` VARCHAR(191) NOT NULL,

    UNIQUE INDEX `EMPRESA_NIT_EMPRESA_key`(`NIT_EMPRESA`),
    PRIMARY KEY (`ID_EMPRESA`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `PRACTICA_PROFESIONAL` (
    `ID_TRABAJO_GRADO` INTEGER NOT NULL,
    `ID_EMPRESA` INTEGER NOT NULL,
    `NOMBRE_SUPERVISOR` VARCHAR(191) NOT NULL,
    `CARGO_SUPERVISOR` VARCHAR(191) NOT NULL,
    `FECHA_INICIO` DATETIME(3) NOT NULL,
    `FECHA_FIN` DATETIME(3) NULL,
    `NUMERO_CONSTANCIA_ARL` VARCHAR(191) NULL,
    `ESTADO_PRACTICA` VARCHAR(191) NOT NULL,

    PRIMARY KEY (`ID_TRABAJO_GRADO`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `EVALUACION_TG` (
    `ID_EVALUACION` INTEGER NOT NULL AUTO_INCREMENT,
    `ID_TRABAJO_GRADO` INTEGER NOT NULL,
    `CARNET_EVALUADOR` VARCHAR(191) NOT NULL,
    `TIPO_EVALUACION` VARCHAR(191) NOT NULL,
    `FECHA_EVALUACION` DATETIME(3) NOT NULL,
    `CALIFICACION` INTEGER NOT NULL,
    `OBSERVACIONES` VARCHAR(191) NULL,
    `CONCEPTO` VARCHAR(191) NULL,

    PRIMARY KEY (`ID_EVALUACION`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `SUSTENTACION` (
    `ID_SUSTENTACION` INTEGER NOT NULL AUTO_INCREMENT,
    `ID_TRABAJO_GRADO` INTEGER NOT NULL,
    `FECHA_SUSTENTACION` DATETIME(3) NOT NULL,
    `LUGAR` VARCHAR(191) NOT NULL,
    `CALIFICACION_FINAL` INTEGER NOT NULL,
    `DISTINCION` VARCHAR(191) NOT NULL,
    `NUMERO_RESOLUCION` VARCHAR(191) NULL,
    `FECHA_RESOLUCION` DATETIME(3) NULL,

    UNIQUE INDEX `SUSTENTACION_ID_TRABAJO_GRADO_key`(`ID_TRABAJO_GRADO`),
    PRIMARY KEY (`ID_SUSTENTACION`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `PROGRAMA_ACADEMICO` ADD CONSTRAINT `PROGRAMA_ACADEMICO_ID_FACULTAD_fkey` FOREIGN KEY (`ID_FACULTAD`) REFERENCES `FACULTAD`(`ID_FACULTAD`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `PROGRAMA_NIVEL` ADD CONSTRAINT `PROGRAMA_NIVEL_ID_PROGRAMA_ACADEMICO_fkey` FOREIGN KEY (`ID_PROGRAMA_ACADEMICO`) REFERENCES `PROGRAMA_ACADEMICO`(`ID_PROGRAMA_ACADEMICO`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `PROGRAMA_NIVEL` ADD CONSTRAINT `PROGRAMA_NIVEL_ID_NIVEL_FORMACION_fkey` FOREIGN KEY (`ID_NIVEL_FORMACION`) REFERENCES `NIVEL_FORMACION`(`ID_NIVEL_FORMACION`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `OPCION_GRADO` ADD CONSTRAINT `OPCION_GRADO_ID_PROGRAMA_NIVEL_fkey` FOREIGN KEY (`ID_PROGRAMA_NIVEL`) REFERENCES `PROGRAMA_NIVEL`(`ID_PROGRAMA_NIVEL`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `ESTUDIANTE_PROGRAMA` ADD CONSTRAINT `ESTUDIANTE_PROGRAMA_CARNET_fkey` FOREIGN KEY (`CARNET`) REFERENCES `PERSONA`(`CARNET`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `ESTUDIANTE_PROGRAMA` ADD CONSTRAINT `ESTUDIANTE_PROGRAMA_ID_PROGRAMA_ACADEMICO_fkey` FOREIGN KEY (`ID_PROGRAMA_ACADEMICO`) REFERENCES `PROGRAMA_ACADEMICO`(`ID_PROGRAMA_ACADEMICO`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `TRABAJO_GRADO` ADD CONSTRAINT `TRABAJO_GRADO_ID_OPCION_GRADO_fkey` FOREIGN KEY (`ID_OPCION_GRADO`) REFERENCES `OPCION_GRADO`(`ID_OPCION_GRADO`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `TRABAJO_GRADO` ADD CONSTRAINT `TRABAJO_GRADO_ID_ESTADO_ACTUAL_fkey` FOREIGN KEY (`ID_ESTADO_ACTUAL`) REFERENCES `ESTADO_TG`(`ID_ESTADO_TG`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `ROL_PERSONA_TG` ADD CONSTRAINT `ROL_PERSONA_TG_CARNET_fkey` FOREIGN KEY (`CARNET`) REFERENCES `PERSONA`(`CARNET`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `ROL_PERSONA_TG` ADD CONSTRAINT `ROL_PERSONA_TG_ID_TRABAJO_GRADO_fkey` FOREIGN KEY (`ID_TRABAJO_GRADO`) REFERENCES `TRABAJO_GRADO`(`ID_TRABAJO_GRADO`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `ROL_PERSONA_TG` ADD CONSTRAINT `ROL_PERSONA_TG_ID_TIPO_ROL_fkey` FOREIGN KEY (`ID_TIPO_ROL`) REFERENCES `TIPO_ROL`(`ID_TIPO_ROL`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `SEGUIMIENTO_TG` ADD CONSTRAINT `SEGUIMIENTO_TG_ID_TRABAJO_GRADO_fkey` FOREIGN KEY (`ID_TRABAJO_GRADO`) REFERENCES `TRABAJO_GRADO`(`ID_TRABAJO_GRADO`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `SEGUIMIENTO_TG` ADD CONSTRAINT `SEGUIMIENTO_TG_CARNET_ACTOR_fkey` FOREIGN KEY (`CARNET_ACTOR`) REFERENCES `PERSONA`(`CARNET`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `SEGUIMIENTO_TG` ADD CONSTRAINT `SEGUIMIENTO_TG_ID_ESTADO_ANTERIOR_fkey` FOREIGN KEY (`ID_ESTADO_ANTERIOR`) REFERENCES `ESTADO_TG`(`ID_ESTADO_TG`) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `SEGUIMIENTO_TG` ADD CONSTRAINT `SEGUIMIENTO_TG_ID_ESTADO_NUEVO_fkey` FOREIGN KEY (`ID_ESTADO_NUEVO`) REFERENCES `ESTADO_TG`(`ID_ESTADO_TG`) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `PRACTICA_PROFESIONAL` ADD CONSTRAINT `PRACTICA_PROFESIONAL_ID_TRABAJO_GRADO_fkey` FOREIGN KEY (`ID_TRABAJO_GRADO`) REFERENCES `TRABAJO_GRADO`(`ID_TRABAJO_GRADO`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `PRACTICA_PROFESIONAL` ADD CONSTRAINT `PRACTICA_PROFESIONAL_ID_EMPRESA_fkey` FOREIGN KEY (`ID_EMPRESA`) REFERENCES `EMPRESA`(`ID_EMPRESA`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `EVALUACION_TG` ADD CONSTRAINT `EVALUACION_TG_ID_TRABAJO_GRADO_fkey` FOREIGN KEY (`ID_TRABAJO_GRADO`) REFERENCES `TRABAJO_GRADO`(`ID_TRABAJO_GRADO`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `EVALUACION_TG` ADD CONSTRAINT `EVALUACION_TG_CARNET_EVALUADOR_fkey` FOREIGN KEY (`CARNET_EVALUADOR`) REFERENCES `PERSONA`(`CARNET`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `SUSTENTACION` ADD CONSTRAINT `SUSTENTACION_ID_TRABAJO_GRADO_fkey` FOREIGN KEY (`ID_TRABAJO_GRADO`) REFERENCES `TRABAJO_GRADO`(`ID_TRABAJO_GRADO`) ON DELETE RESTRICT ON UPDATE CASCADE;
