import swaggerJsdoc, { Options } from "swagger-jsdoc";
import { envs } from "./envs";
import { buildComponentSchemas } from "./swagger-from-validator";
import {
  RegisterSchema,
  UserConfirmationSchema,
  UserLoginSchema,
  ForgotPasswordSchema,
  ResetPasswordSchema,
  UpdatePasswordSchema,
  CheckAuthUserPasswordSchema,
} from "../auth/auth.schema";

// Componentes de request generados automáticamente desde los Schemas de
// express-validator. Para agregar uno nuevo, registralo acá con el nombre que
// quieras exponer en el spec — los `$ref` en los JSDoc deben usar este nombre.
const autoGeneratedRequestSchemas = buildComponentSchemas({
  RegisterRequest: RegisterSchema,
  TokenBody: UserConfirmationSchema,
  LoginRequest: UserLoginSchema,
  EmailBody: ForgotPasswordSchema,
  ResetPasswordBody: ResetPasswordSchema,
  UpdatePasswordBody: UpdatePasswordSchema,
  CheckPasswordBody: CheckAuthUserPasswordSchema,
});

const options: Options = {
  definition: {
    openapi: "3.0.3",
    info: {
      title: "UniMayor API",
      version: "1.0.0",
      description:
        "API del sistema de gestión de trabajos de grado y proyección social — UniMayor.",
    },
    servers: [
      {
        url: `http://localhost:${envs.PORT}`,
        description: "Local",
      },
    ],
    tags: [
      {
        name: "Auth",
        description:
          "Registro, login, confirmación de cuenta y manejo de contraseñas.",
      },
      {
        name: "Health",
        description: "Comprobación de estado de la API.",
      },
    ],
    components: {
      securitySchemes: {
        bearerAuth: {
          type: "http",
          scheme: "bearer",
          bearerFormat: "JWT",
        },
      },
      schemas: {
        // Schemas de respuesta / utilitarios (no salen de un validador).
        Error: {
          type: "object",
          properties: {
            error: { type: "string", example: "Mensaje descriptivo del error" },
          },
        },
        ValidationError: {
          type: "object",
          properties: {
            errors: {
              type: "array",
              items: {
                type: "object",
                properties: {
                  type: { type: "string", example: "field" },
                  msg: { type: "string", example: "Email is required" },
                  path: { type: "string", example: "email" },
                  location: { type: "string", example: "body" },
                },
              },
            },
          },
        },
        User: {
          type: "object",
          properties: {
            id_persona: { type: "string", example: "ckxyz..." },
            nombres: { type: "string", example: "Juan" },
            apellidos: { type: "string", example: "Pérez" },
            correo_electronico: { type: "string", format: "email" },
            num_doc_identidad: { type: "string" },
            numero_celular: { type: "string" },
            confirmed: { type: "boolean" },
          },
        },
        LoginResponse: {
          type: "object",
          properties: {
            token: { type: "string", description: "JWT firmado", example: "eyJhbGciOi..." },
            user: { $ref: "#/components/schemas/User" },
          },
        },
        MessageResponse: {
          type: "object",
          properties: {
            message: { type: "string", example: "Operación realizada correctamente" },
          },
        },
        // Schemas de request generados desde express-validator
        ...autoGeneratedRequestSchemas,
      },
    },
    security: [{ bearerAuth: [] }],
  },
  apis: [
    "./src/server.ts",
    "./src/**/*.routes.ts",
    "./src/**/*.controller.ts",
  ],
};

export const swaggerSpec = swaggerJsdoc(options);
