-- AlterTable
ALTER TABLE `PERSONA` ADD COLUMN `id_facultad` VARCHAR(191) NULL;

-- AddForeignKey
ALTER TABLE `PERSONA` ADD CONSTRAINT `PERSONA_id_facultad_fkey` FOREIGN KEY (`id_facultad`) REFERENCES `FACULTAD`(`id_facultad`) ON DELETE SET NULL ON UPDATE CASCADE;
